server:
  port: ${SERVER_PORT:8090}

spring:
  application:
    name: cash-service

  config:
    import: 'kubernetes:'

  cloud:
    kubernetes:
      config:
        enabled: true
        name: api-gateway
        namespace: default
        fail-fast: true
        include-profile-specific-sources: false