server:
  port: 8065

spring:
  application:
    name: transfers-service

  config:
    import: 'consul:'

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        hostname: localhost
        port: ${server.port}
        register-health-check: false
      config:
        format: YAML
        enabled: true
        fail-fast: true
        defaultContext: application