server:
  port: ${SERVER_PORT:8065}

spring:
  application:
    name: transfers-service

  config:
    import: 'kubernetes:'

  cloud:
    kubernetes:
      discovery:
        enabled: true
        namespaces: default
      config:
        enabled: true
        name: account-service
        namespace: default
        fail-fast: true
        include-profile-specific-sources: false